import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'

const navigationConfig = [
    {
        key: 'apps',
        path: '',
        title: '',
        translateKey: 'nav.apps',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin', 'user'],
        subMenu: [
            {
                key: 'dashboard',
                path: '/home',
                title: 'Dashboard',
                translateKey: 'nav.dashboard',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin', 'user'],
                subMenu: [],
            },

            {
                key: 'collapseProfile',
                path: '',
                title: 'บัญชีผู้ใช้',
                translateKey: 'nav.collapseProfile.reports',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['admin', 'user'],
                subMenu: [
                    {
                        key: 'collapseProfile.item1',
                        path: '/account/settings/profile',
                        title: 'Reports 1',
                        translateKey: 'nav.collapseProfile.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'collapseProfile.item2',
                        path:'/change-password',
                        title: 'Reports 2',
                        translateKey: 'nav.collapseProfile.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },

            {
                key: 'collapseReports',
                path: '',
                title: 'Reports',
                translateKey: 'nav.collapseReports.reports',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: ['admin', 'user'],
                subMenu: [
                    {
                        key: 'collapseReports.item1',
                        path: '/dailyOverview',
                        title: 'Reports 1',
                        translateKey: 'nav.collapseReports.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'collapseReports.item2',
                        path: '/monthlyCommission',
                        title: 'Reports 2',
                        translateKey: 'nav.collapseReports.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'collapseReports.item3',
                        path: '/dayCommission',
                        title: 'Reports 3',
                        translateKey: 'nav.collapseReports.item3',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'collapseReports.item4',
                        path: '/receivedPercentage',
                        title: 'Reports 4',
                        translateKey: 'nav.collapseReports.item4',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'collapseReports.item5',
                        path: '/userRank',
                        title: 'Reports 5',
                        translateKey: 'nav.collapseReports.item5',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
           
        ],
    },
   
    /** Example purpose only, please remove */

    {
        key: '',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'groupMenu.editAgent',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.editAgent.editAgent',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.editAgent.item1',
                        path: '/editDataAgent',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.editAgent.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },

                    {
                        key: 'groupMenu.editAgent.item2',
                        path: 'agent/addAgent',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.editAgent.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'groupMenu.editGame',
                path: '',
                title: 'Group single menu item',
                translateKey: 'nav.groupMenu.editGame.editGame',
                icon: 'groupSingleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.editGame.item1',
                        path: '/Game/DemoGame',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.editGame.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.editGame.item2',
                        path: '/Game/WinRate',
                        title: 'Menu item 2',
                        translateKey: 'nav.groupMenu.editGame.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
           /* {
                key: 'groupMenu.apis',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.apis.apis',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.apis.item1',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.apis.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },*/
            {
                key: 'groupMenu.userManual',
                path: '',
                title: 'Group collapse menu',
                translateKey: 'nav.groupMenu.userManual.userManual',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'groupMenu.userManual.item1',
                        path: '/manual/add-credit-user',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.userManual.item1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'groupMenu.userManual.item2',
                        path: '/manual/add-member-user',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.userManual.item2',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    /*{
                        key: 'groupMenu.userManual.item3',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.userManual.item3',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },*/
                    {
                        key: 'groupMenu.userManual.item4',
                        path: '/manual/graph',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.userManual.item4',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                   /* {
                        key: 'groupMenu.userManual.item5',
                        path: '/group-collapse-menu-item-view-1',
                        title: 'Menu item 1',
                        translateKey: 'nav.groupMenu.userManual.item5',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },*/
                ],
            },
            {
                key: 'groupMenu.condition',
                path: '/conditionGame',
                title: 'เงื่อนไขและข้อตกลง',
                translateKey: 'nav.groupMenu.condition.condition',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [],
            },
            {
                key: 'groupMenu.updatereport',
                path: 'System-Changelogs',
                title: 'รายงานการอัพเดทระบบ',
                translateKey: 'nav.groupMenu.updatereport.updatereport',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [],
            },
           /* {
                key: 'groupMenu.manual',
                path: '',
                title: 'คู่มือการใช้งาน Demo',
                translateKey: 'nav.groupMenu.manual.manual',
                icon: 'groupCollapseMenu',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [],
            },*/
        ],
    },
]

export default navigationConfig
